mixed-port: 7890
allow-lan: true
mode: Rule
ipv6: true
external-controller: :9999
external-ui: ui
interface-name: pppoe-wan
tun:
  enable: true
  stack: system
  dns-hijack:
    - 119.29.29.29:53
    - 119.28.28.28:53
    - 223.5.5.5:53
    - 223.6.6.6:53
    - 1.2.4.8:53
    - 182.254.116.116:53
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  nameserver:
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
  fallback:
    - tls://1.0.0.1:853
    - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
store-selected: true
