#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

start_service() {
    procd_open_instance
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param command /etc/clash/start_clash.sh
    procd_close_instance
}

stop_service() {
    killall clash
    iptables -t mangle -F PREROUTING
    iptables -t mangle -F CLASH
    iptables -t mangle -X CLASH
    iptables -t nat -D PREROUTING -p tcp --dport 53 -j REDIRECT --to 1053
    iptables -t nat -D PREROUTING -p udp --dport 53 -j REDIRECT --to 1053
    ip6tables -t nat -D PREROUTING -p tcp --dport 53 -j REDIRECT --to 1053
    ip6tables -t nat -D PREROUTING -p udp --dport 53 -j REDIRECT --to 1053
}
